# Builds Backend with Maven
# Checks with supported OpenJDK versions, currently 8 and 11.

name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ '8.0.265', '11.0.4' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file esd-api/pom.xml
