# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8.0u265
      uses: actions/setup-java@v1
      with:
        java-version: 8.0.265
    - name: Build with Maven
      run: mvn -B package --file esd-api/pom.xml
