# This workflow will run ci and then eslint on the frontend for new PRs.

name: Node.js PR checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd esd-ui/ && npm ci
      - run: cd esd-ui/ && npm run eslint
